---
- name: Configure 3 VRFs with static routes - classic ip vrf syntax
  hosts: routers
  gather_facts: no
  tasks:
    - name: Create VRFs using classic syntax
      ios_config:
        lines:
          - ip vrf RED
          - ip vrf GREEN
          - ip vrf BLUE

    - name: Configure physical interface as trunk (no IP)
      ios_config:
        lines:
          - no ip address
          - description SINGLE TRUNK LINK FOR ALL VRFS
        parents: interface GigabitEthernet4/0

    - name: Configure subinterfaces and assign to VRFs
      ios_config:
        lines:
          - encapsulation dot1Q {{ item.vlan }}
          - ip vrf forwarding {{ item.vrf }}
          - ip address {{ item.ip }} 255.255.255.0
          - no shutdown
          - description {{ item.vrf }} SUBINTERFACE
        parents: interface GigabitEthernet4/0.{{ item.vlan }}
      loop:
        - { vlan: 10, vrf: RED,   ip: "{{ '172.16.10.1' if inventory_hostname == 'R1' else '172.16.10.2' }}" }
        - { vlan: 20, vrf: GREEN, ip: "{{ '172.16.20.1' if inventory_hostname == 'R1' else '172.16.20.2' }}" }
        - { vlan: 30, vrf: BLUE,  ip: "{{ '172.16.30.1' if inventory_hostname == 'R1' else '172.16.30.2' }}" }

    - name: Create VRF-aware loopbacks
      ios_config:
        lines:
          - ip vrf forwarding {{ item.vrf }}
          - ip address {{ item.loopback }} 255.255.255.255
          - no shutdown
          - description LOOPBACK FOR {{ item.vrf }}
        parents: interface Loopback{{ item.vlan }}
      loop:
        - { vlan: 10, vrf: RED,   loopback: "{{ '1.1.1.1' if inventory_hostname == 'R1' else '1.1.1.2' }}" }
        - { vlan: 20, vrf: GREEN, loopback: "{{ '2.2.2.1' if inventory_hostname == 'R1' else '2.2.2.2' }}" }
        - { vlan: 30, vrf: BLUE,  loopback: "{{ '3.3.3.1' if inventory_hostname == 'R1' else '3.3.3.2' }}" }

    - name: Add static routes for remote loopbacks
      ios_config:
        lines:
          - ip route vrf {{ item.vrf }} {{ item.remote_loopback }} 255.255.255.255 {{ item.next_hop }}
      loop:
        - { vrf: RED,   remote_loopback: "{{ '1.1.1.2' if inventory_hostname == 'R1' else '1.1.1.1' }}", next_hop: "{{ '172.16.10.2' if inventory_hostname == 'R1' else '172.16.10.1' }}" }
        - { vrf: GREEN, remote_loopback: "{{ '2.2.2.2' if inventory_hostname == 'R1' else '2.2.2.1' }}", next_hop: "{{ '172.16.20.2' if inventory_hostname == 'R1' else '172.16.20.1' }}" }
        - { vrf: BLUE,  remote_loopback: "{{ '3.3.3.2' if inventory_hostname == 'R1' else '3.3.3.1' }}", next_hop: "{{ '172.16.30.2' if inventory_hostname == 'R1' else '172.16.30.1' }}" }

    - name: Save configuration
      ios_command:
        commands:
          - write memory